/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculo;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import org.mariuszgromada.math.mxparser.Function;

/**
 *
 * @author Mauricio Castillo
 */
public class GraficoGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form Gráfico
     */
    private InitGUI ventanaPrincipal;
    private IntegralGUI integral;
    private String funcionString, metodo;
    private Function funcion;
    private FunctionVisualizer visualizador;
    private double valorA,valorB,valorX;
    
    private Double resultado;
    private int indicadorMetodo;
    
    /**
     *
     * @param ventanaPrincipal
     * @param funcion
     * @param indicadorMetodo
     */
    public GraficoGUI(InitGUI ventanaPrincipal, Function funcion,
            int indicadorMetodo) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        this.funcion = funcion;
        this.funcionString = funcion.getFunctionExpressionString();
        funcionLabel.setText("Función = "+funcionString);
        this.setTitle(ventanaPrincipal.getTitle());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.indicadorMetodo = indicadorMetodo;
    }
    
    /**
     *
     * @param gui
     */
    public void setVentana(IntegralGUI gui){
        this.integral = gui;
    }
    
    /**
     *
     * @param valorA
     * @param valorB
     * @param resultado
     * @param metodo
     */
    public void setIntegralValues(double valorA, double valorB,
            double resultado, String metodo){
        this.valorA = valorA;
        this.valorB = valorB;
        this.resultado = resultado;
        this.metodo = metodo;
    }
    
    /**
     *
     * @param valorX
     * @param resultado
     * @param metodo
     */
    public void setLimitValues(double valorX,Double resultado,String metodo){
        this.valorX = valorX;
        this.resultado = resultado;
        this.metodo = metodo;
    }
    
    /**
     *
     */
    public void setGrafica(){
        panelGrafico.setLayout(new java.awt.BorderLayout());
        
        if(indicadorMetodo == 1){
            visualizador = new FunctionVisualizer(funcion, valorX);
            if (resultado == null){
                respuestaSalida.setText("infinito");
            }else{
                respuestaSalida.setText(resultado.toString());
            }
        }
        if(indicadorMetodo == 2){
            
        }
        if(indicadorMetodo == 3){
            visualizador = new FunctionVisualizer(funcion, valorA, valorB);
            respuestaSalida.setText(resultado.toString());
        }
        panelGrafico.removeAll();
        panelGrafico.add(visualizador.creacionGrafico(),BorderLayout.CENTER);
        panelGrafico.validate();
        mensajeLabel.setText("El resultado del método: "+metodo+" es:");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGrafico = new javax.swing.JPanel();
        funcionLabel = new javax.swing.JLabel();
        mensajeLabel = new javax.swing.JLabel();
        respuestaSalida = new javax.swing.JTextField();
        menuPrincipal = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelGrafico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        funcionLabel.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        funcionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funcionLabel.setText("Función");

        mensajeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mensajeLabel.setText("Salida");

        respuestaSalida.setEditable(false);
        respuestaSalida.setText("Respuesta");

        menuPrincipal.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        menuPrincipal.setText("Menú Principal");
        menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(funcionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mensajeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(respuestaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(funcionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensajeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuestaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        if(indicadorMetodo == 3){
            integral.setEnabled(true);
            integral.setVisible(true);
            integral.setStateButtons();
        }else{
            ventanaPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalActionPerformed
        
        if(indicadorMetodo == 3){
            integral.setVisible(false);
        }
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPrincipalActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel funcionLabel;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JButton menuPrincipal;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JTextField respuestaSalida;
    // End of variables declaration//GEN-END:variables
}
