/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculo;

import javax.swing.JFrame;
import org.mariuszgromada.math.mxparser.*;

/**
 *
 * @author Mauricio Castillo
 */
public class InitGUI extends javax.swing.JFrame {

    /**
     * Creates new form InitGUI
     */
    private String funcionString;
    private Function funcionInicial;
    
    public InitGUI() {
        initComponents();
        this.setTitle("Cálculo por Métodos Numéricos");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.deActivateButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta1 = new javax.swing.JLabel();
        funcion = new javax.swing.JTextField();
        almacenar = new javax.swing.JButton();
        limiteBoton = new javax.swing.JButton();
        derivadaBoton = new javax.swing.JButton();
        integralBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setForeground(java.awt.Color.blue);
        setResizable(false);

        etiqueta1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        etiqueta1.setText("Resolución de una Función");

        funcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        funcion.setText("f(x)=");
        funcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionActionPerformed(evt);
            }
        });

        almacenar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        almacenar.setText("Guardar Función");
        almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenarActionPerformed(evt);
            }
        });

        limiteBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        limiteBoton.setText("Límite");
        limiteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limiteBotonActionPerformed(evt);
            }
        });

        derivadaBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        derivadaBoton.setText("Derivada");
        derivadaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derivadaBotonActionPerformed(evt);
            }
        });

        integralBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        integralBoton.setText("Integral");
        integralBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integralBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Función");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(funcion, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(almacenar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(limiteBoton)
                        .addGap(47, 47, 47)
                        .addComponent(derivadaBoton)
                        .addGap(43, 43, 43)
                        .addComponent(integralBoton)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(etiqueta1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(almacenar))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limiteBoton)
                    .addComponent(derivadaBoton)
                    .addComponent(integralBoton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deActivateButtons(){
        limiteBoton.setEnabled(false);
        derivadaBoton.setEnabled(false);
        integralBoton.setEnabled(false);
}
    
    private void activateButtons(){
        limiteBoton.setEnabled(true);
        derivadaBoton.setEnabled(true);
        integralBoton.setEnabled(true);
}
    public boolean checkValue(String texto){
        try{
            Double.parseDouble(texto);
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }
    
    private void funcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionActionPerformed

    private void limiteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limiteBotonActionPerformed
        
        LimGUI limVentana = new LimGUI(this,funcionInicial);
        limVentana.setVisible(true);
        this.setVisible(false);
        this.deActivateButtons();
        this.funcion.setText("f(x)=");
        this.funcionInicial=null;
    }//GEN-LAST:event_limiteBotonActionPerformed

    private void derivadaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derivadaBotonActionPerformed
        
        DerivadaGUI derIVentana = new DerivadaGUI(this,funcionInicial);
        derIVentana.setVisible(true);
        this.setVisible(false);
        this.deActivateButtons();
        this.funcion.setText("f(x)=");
        this.funcionInicial=null;
    }//GEN-LAST:event_derivadaBotonActionPerformed

    private void integralBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integralBotonActionPerformed
        
        IntegralGUI intVentana = new IntegralGUI(this,funcionInicial);
        intVentana.setVisible(true);
        this.setVisible(false);
        this.deActivateButtons();
        this.funcion.setText("f(x)=");
        this.funcionInicial=null;
    }//GEN-LAST:event_integralBotonActionPerformed

    private void almacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenarActionPerformed
        
        funcionInicial = new Function(funcion.getText());
        funcionString = funcionInicial.getFunctionExpressionString();
        if (!funcionString.equals("")){
            this.activateButtons();
            
        }else{
            this.deActivateButtons();
        }
//      //System.out.println(funcionInicial.calculate(6));
        
    }//GEN-LAST:event_almacenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almacenar;
    private javax.swing.JButton derivadaBoton;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JTextField funcion;
    private javax.swing.JButton integralBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton limiteBoton;
    // End of variables declaration//GEN-END:variables
}
